### ISSUE TITLE
What's the name of the integration?

### ISSUE THREAD

**Issue by d8rt8v** [R1p4eg/gismeteo-allergy#2]
Can not find the integration in the drop-down menu

**Comment by D8mbSniper** [comment]
`2023-05-15 23:44:10.345 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'gismeteo_allergy' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`


Seems like it needs an update :)

**Comment by D8mbSniper** [comment]
closing

**Comment by d8rt8v** [comment]
`2023-05-15 23:44:10.345 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'gismeteo_allergy' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`


Seems like it needs an update :)
